#include "lexer.h"
#include <cctype>
#include <filesystem>
#include <fstream>
#include <stdexcept>
namespace{std::string trim(const std::string&s){auto a=s.find_first_not_of(" \t\r\n");if(a==std::string::npos)return{};return s.substr(a,s.find_last_not_of(" \t\r\n")-a+1);}}
Lexer::Lexer(std::string d){loadLanguagePacks(d);if(keywords.empty())keywords={{"print","PRINT"},{"var","VAR"},{"let","VAR"},{"true","TRUE"},{"false","FALSE"},{"none","NONE"},{"if","IF"},{"else","ELSE"},{"while","WHILE"},{"return","RETURN"}};}
void Lexer::loadLanguagePacks(const std::string&d){namespace fs=std::filesystem;std::error_code ec;if(!fs::exists(d,ec))return;for(const auto&e:fs::recursive_directory_iterator(d,ec)){if(ec||!e.is_regular_file()||e.path().extension()!=".asklang")continue;std::ifstream in(e.path(),std::ios::binary);std::string l;while(std::getline(in,l)){l=trim(l);if(l.empty()||l[0]=='#')continue;auto p=l.find('=');if(p==std::string::npos)continue;auto k=trim(l.substr(0,p)),v=trim(l.substr(p+1));if(!k.empty()&&k!="language")keywords[k]=v;}}}
bool Lexer::isIdentifierStart(unsigned char c){return std::isalpha(c)||c=='_'||c>=0x80;}
bool Lexer::isIdentifierContinue(unsigned char c){return std::isalnum(c)||c=='_'||c>=0x80;}
std::vector<Token> Lexer::tokenize(const std::string&s){std::vector<Token>o;std::size_t i=0,l=1,c=1;auto add=[&](std::string t,std::string v,std::size_t a,std::size_t b){o.push_back({std::move(t),std::move(v),a,b});};while(i<s.size()){unsigned char x=s[i];if(x==' '||x=='\t'||x=='\r'){++i;++c;continue;}if(x=='\n'){++i;++l;c=1;continue;}if(x=='/'&&i+1<s.size()&&s[i+1]=='/'){i+=2;c+=2;while(i<s.size()&&s[i]!='\n'){++i;++c;}continue;}auto a=l,b=c;if(x=='"'){++i;++c;std::string v;bool ok=false;while(i<s.size()){char q=s[i];if(q=='"'){++i;++c;ok=true;break;}if(q=='\\'&&i+1<s.size()){char n=s[i+1];v+=(n=='n'?'\n':n=='t'?'\t':n);i+=2;c+=2;}else{v+=q;++i;++c;}}if(!ok)throw std::runtime_error("Unterminated string at "+std::to_string(a)+":"+std::to_string(b));add("STRING",v,a,b);continue;}if(std::isdigit(x)||(x=='.'&&i+1<s.size()&&std::isdigit((unsigned char)s[i+1]))){auto st=i;bool dot=false;while(i<s.size()&&(std::isdigit((unsigned char)s[i])||s[i]=='.')){if(s[i]=='.'){if(dot)break;dot=true;}++i;++c;}add("NUMBER",s.substr(st,i-st),a,b);continue;}if(isIdentifierStart(x)){auto st=i;while(i<s.size()&&isIdentifierContinue((unsigned char)s[i])){++i;++c;}auto v=s.substr(st,i-st);if(v=="amar"||v=="as"||v=="ask"||v=="asika")throw std::runtime_error("Reserved Ask word cannot be used as an identifier at "+std::to_string(a)+":"+std::to_string(b));auto it=keywords.find(v);add(it==keywords.end()?"IDENT":it->second,v,a,b);continue;}std::string two=i+1<s.size()?s.substr(i,2):"";if(two=="=="||two=="!="||two=="<="||two==">="){add(two,two,a,b);i+=2;c+=2;continue;}std::string one(1,(char)x);if(std::string("+-*/%=<>!;(),{}").find(x)!=std::string::npos){add(one,one,a,b);++i;++c;continue;}throw std::runtime_error("Unexpected character at "+std::to_string(a)+":"+std::to_string(b));}add("EOF","",l,c);return o;}